### ISSUE TITLE
Feature request:  `obs_dim` attribute

### ISSUE THREAD

**Issue by enjeeneer** [rdnfn/bauwerk#16]
* bauwerk version: 0.2.1
* Python version: 3.8
* Operating System: macOS

### Description
Afaik, gym environments usually allow you to call `env.observation_space.shape` to access the the obs_space shape. At the moment, Bauwerk's `observation_space` is stored as a Dict so this can't be done. This functionality would be helpful, but maybe you've already implemented it? If so, apologies for the redundant request!

**Comment by rdnfn** [comment]
Thanks for raising this issue!

This can already be done, albeit in a slightly more complicated manner. You can access it per dict entry, e.g.

```python
env.observation_space["battery_cont"].shape
```

Closing this issue but feel free to reopen if this does not resolve your problem.
