### ISSUE TITLE
`env.observation_space.high` does not define the true maximum observations in the dataset

### ISSUE THREAD

**Issue by enjeeneer** [rdnfn/bauwerk#18]
* bauwerk version: 0.21
* Python version: 3.8
* Operating System: macOS

### Description
The hard-coded upper limit on `env.observation_space` is unrealistically high for the `load` and `pv_gen` variables (dims 1 and 2 of the array printed below) i.e.

```
obs_high = []
for key, _ in env.observation_space.items():
    obs_high.append(env.observation_space[key].high)

print(np.concatenate(obs_high))

[7.500e+00 3.403e+38 3.403e+38 1.000e+00 1.000e+00]
```  

This becomes problematic when one attempts to normalise the observation space using the floor `env.observation_space.low` and ceiling `env.observation_space.high`.

Looking through the repo, it seems the max value might be the `load_scaling_factor` and `solar_scaling_factor` for the `load` and `pv_gen` variables respectively? I see that `default_load_data.txt` and `default_solar_data.txt` are in [0, 1], and the `load` and `pv_gen` observations are the values from the .txt file multiplied by the scaling factor. Thoughts?

**Comment by rdnfn** [comment]
Good news: the suggested update to the obs spaces has been implemented and a normalisation wrapper added with v0.3.0. Thus closing this issue.
